# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-28 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('univercity', models.CharField(blank=True, default='Where Did You Learn ?', max_length=45, null=True)),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('degree', models.CharField(blank=True, default='Which Degree Did You Earn ?', max_length=45, null=True)),
                ('descriptions', models.CharField(blank=True, default='Description about education', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, default='Where Did You Work', max_length=45, null=True)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.CharField(blank=True, default='Say Something About Your Job', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(default='0', max_length=50)),
                ('title', models.CharField(default='0', max_length=50)),
                ('organization', models.CharField(default='0', max_length=50)),
                ('about_company', models.CharField(default='0', max_length=8000)),
                ('job_description', models.CharField(default='0', max_length=8000)),
                ('open_date', models.CharField(default='0', max_length=50)),
                ('closing_date', models.CharField(default='0', max_length=50)),
                ('number_vacancies', models.CharField(default='0', max_length=50)),
                ('functional_area', models.CharField(default='0', max_length=50)),
                ('nationality', models.CharField(default='0', max_length=50)),
                ('contract_type', models.CharField(default='0', max_length=50)),
                ('contract_duration', models.CharField(default='0', max_length=50)),
                ('probation_period', models.CharField(default='0', max_length=50)),
                ('reference', models.CharField(default='0', max_length=50)),
                ('work_type', models.CharField(default='0', max_length=50)),
                ('gender', models.CharField(default='0', max_length=20)),
                ('open_ended', models.CharField(default='0', max_length=50)),
                ('salary_range', models.CharField(default='0', max_length=50)),
                ('year_of_expirence', models.CharField(default='0', max_length=50)),
                ('extension_passibility', models.CharField(default='0', max_length=50)),
                ('duties_responsibilities', models.CharField(default='0', max_length=8000)),
                ('skills', models.CharField(default='0', max_length=8000)),
                ('qualification', models.CharField(default='0', max_length=8000)),
                ('jobs_location', models.CharField(default='0', max_length=8000)),
                ('education', models.CharField(default='0', max_length=100)),
                ('submission_guideline', models.CharField(default='0', max_length=8000)),
                ('submission_email', models.CharField(default='0', max_length=50)),
                ('website', models.CharField(default='0', max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobsRelated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_des', models.FloatField(blank=True, default=0, null=True)),
                ('weight_req', models.FloatField(blank=True, default=0, null=True)),
                ('weight', models.FloatField(blank=True, default=0, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs_related', to='jobs.Jobs')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=45, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=45, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpiderData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(default='0', max_length=50)),
                ('title', models.CharField(default='0', max_length=50)),
                ('organization', models.CharField(default='0', max_length=50)),
                ('about_company', models.CharField(default='0', max_length=8000)),
                ('job_description', models.CharField(default='0', max_length=8000)),
                ('open_date', models.CharField(default='0', max_length=50)),
                ('closing_date', models.CharField(default='0', max_length=50)),
                ('number_vacancies', models.CharField(default='0', max_length=50)),
                ('functional_area', models.CharField(default='0', max_length=50)),
                ('nationality', models.CharField(default='0', max_length=50)),
                ('contract_type', models.CharField(default='0', max_length=50)),
                ('contract_duration', models.CharField(default='0', max_length=50)),
                ('probation_period', models.CharField(default='0', max_length=50)),
                ('reference', models.CharField(default='0', max_length=50)),
                ('work_type', models.CharField(default='0', max_length=50)),
                ('gender', models.CharField(default='0', max_length=20)),
                ('open_ended', models.CharField(default='0', max_length=50)),
                ('salary_range', models.CharField(default='0', max_length=50)),
                ('year_of_expirence', models.CharField(default='0', max_length=50)),
                ('extension_passibility', models.CharField(default='0', max_length=50)),
                ('duties_responsibilities', models.CharField(default='0', max_length=8000)),
                ('skills', models.CharField(default='0', max_length=8000)),
                ('qualification', models.CharField(default='0', max_length=8000)),
                ('jobs_location', models.CharField(default='0', max_length=8000)),
                ('education', models.CharField(default='0', max_length=100)),
                ('submission_guideline', models.CharField(default='0', max_length=8000)),
                ('submission_email', models.CharField(default='0', max_length=50)),
                ('website', models.CharField(default='0', max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrBrowserSeen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(default='0', max_length=512)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interst_and_activites', models.CharField(blank=True, default='say something about yourself ', max_length=500, null=True)),
                ('profession', models.CharField(blank=True, default='Proffession ?', max_length=300, null=True)),
                ('email', models.CharField(blank=True, default='YourEmail@example.com', max_length=45, null=True)),
                ('phone', models.CharField(blank=True, default='9300', max_length=45, null=True)),
                ('tags', models.CharField(blank=True, default='no tags', max_length=250, null=True)),
                ('address', models.CharField(blank=True, default='no address', max_length=250, null=True)),
                ('direction', models.CharField(blank=True, default='nod', max_length=45, null=True)),
                ('educations', models.ManyToManyField(to='jobs.Education')),
                ('experiances', models.ManyToManyField(to='jobs.Experiance')),
                ('languages', models.ManyToManyField(to='jobs.Language')),
            ],
        ),
        migrations.CreateModel(
            name='UserResumeRelated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_des', models.FloatField(blank=True, default=0, null=True)),
                ('weight_req', models.FloatField(blank=True, default=0, null=True)),
                ('weight', models.FloatField(blank=True, default=0, null=True)),
                ('resumes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userresume_related', to='jobs.UserResume')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='UserShortlisted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(default='0', max_length=512)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userresume',
            name='resume_related_to',
            field=models.ManyToManyField(to='jobs.UserResumeRelated'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='skills',
            field=models.ManyToManyField(to='jobs.Skills'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='top_jobs',
            field=models.ManyToManyField(to='jobs.Jobs'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resume', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobs',
            name='jobs_related_to',
            field=models.ManyToManyField(to='jobs.JobsRelated'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='top_condidates',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobs',
            name='user_browser_seen',
            field=models.ManyToManyField(to='jobs.UserOrBrowserSeen'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='user_shortlisted',
            field=models.ManyToManyField(to='jobs.UserShortlisted'),
        ),
        migrations.AlterIndexTogether(
            name='usershortlisted',
            index_together=set([('token',)]),
        ),
        migrations.AlterIndexTogether(
            name='userorbrowserseen',
            index_together=set([('token',)]),
        ),
        migrations.AlterIndexTogether(
            name='jobs',
            index_together=set([('job_description', 'duties_responsibilities')]),
        ),
    ]
