# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-29 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='education',
            name='descriptions',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='education',
            name='univercity',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='experiance',
            name='company',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='experiance',
            name='description',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='about_company',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='closing_date',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='contract_duration',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='contract_type',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='duties_responsibilities',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='education',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='extension_passibility',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='functional_area',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='gender',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='item_id',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobs_location',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='nationality',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='number_vacancies',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='open_date',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='open_ended',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='organization',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='probation_period',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='qualification',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='reference',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary_range',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='skills',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='submission_email',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='submission_guideline',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='website',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='work_type',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='year_of_expirence',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='about_company',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='closing_date',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='contract_duration',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='contract_type',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='duties_responsibilities',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='education',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='extension_passibility',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='functional_area',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='gender',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='item_id',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='job_description',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='jobs_location',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='nationality',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='number_vacancies',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='open_date',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='open_ended',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='organization',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='probation_period',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='qualification',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='reference',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='salary_range',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='skills',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='submission_email',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='submission_guideline',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='title',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='website',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='work_type',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='year_of_expirence',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='userorbrowserseen',
            name='token',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='address',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='direction',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='email',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='interst_and_activites',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='phone',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='profession',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='tags',
            field=models.TextField(default='Default Text'),
        ),
        migrations.AlterField(
            model_name='usershortlisted',
            name='token',
            field=models.TextField(default='Default Text'),
        ),
    ]
